const items = [
  {
    ItemId: 10,
    name: "Ergonomic Office Chair",
    category: "Furniture",
    image: "https://example.com/images/ergonomic-office-chair.jpg",
    newPrice: 300,
    oldPrice: 350,
    color: "Gray",
    description: "A comfortable ergonomic office chair for long working hours.",
    availability: true,
    rentalPrice: 20,
    rentalDurationOptions: [1, 3, 6],
    material: "Mesh",
    weight: 15,
    stockQuantity: 8,
    location: "Warehouse B",
    ratings: {
      averageRating: 4.7,
      numberOfRatings: 85,
    },
  },
  {
    ItemId: 11,
    name: "Stainless Steel Water Bottle",
    category: "Accessories",
    image: "https://example.com/images/stainless-steel-water-bottle.jpg",
    newPrice: 25,
    oldPrice: 30,
    color: "Silver",
    description: "A durable stainless steel water bottle for everyday use.",
    availability: true,
    rentalPrice: 3,
    rentalDurationOptions: [1, 2, 4],
    material: "Stainless Steel",
    weight: 0.5,
    stockQuantity: 50,
    location: "Warehouse C",
    ratings: {
      averageRating: 4.5,
      numberOfRatings: 200,
    },
  },
  {
    ItemId: 12,
    name: "Bluetooth Speaker",
    category: "Electronics",
    image: "https://example.com/images/bluetooth-speaker.jpg",
    newPrice: 60,
    oldPrice: 80,
    color: "Blue",
    description: "A portable Bluetooth speaker with superior sound quality.",
    availability: true,
    rentalPrice: 10,
    rentalDurationOptions: [2, 4, 6],
    material: "Plastic",
    weight: 1,
    stockQuantity: 30,
    location: "Warehouse D",
    ratings: {
      averageRating: 4.3,
      numberOfRatings: 150,
    },
  },
  {
    ItemId: 13,
    name: "Yoga Mat",
    category: "Fitness",
    image: "https://example.com/images/yoga-mat.jpg",
    newPrice: 40,
    oldPrice: 50,
    color: "Green",
    description:
      "A high-quality yoga mat for a comfortable workout experience.",
    availability: true,
    rentalPrice: 5,
    rentalDurationOptions: [1, 3, 6],
    material: "Foam",
    weight: 1.2,
    stockQuantity: 40,
    location: "Warehouse E",
    ratings: {
      averageRating: 4.6,
      numberOfRatings: 120,
    },
  },
  {
    ItemId: 14,
    name: "Electric Kettle",
    category: "Appliances",
    image: "https://example.com/images/electric-kettle.jpg",
    newPrice: 35,
    oldPrice: 45,
    color: "White",
    description: "A fast-boiling electric kettle for quick and easy hot water.",
    availability: true,
    rentalPrice: 7,
    rentalDurationOptions: [1, 3, 6],
    material: "Plastic",
    weight: 1.5,
    stockQuantity: 25,
    location: "Warehouse F",
    ratings: {
      averageRating: 4.4,
      numberOfRatings: 95,
    },
  },
  {
    ItemId: 15,
    name: "Wireless Headphones",
    category: "Electronics",
    image: "https://example.com/images/wireless-headphones.jpg",
    newPrice: 120,
    oldPrice: 150,
    color: "Black",
    description: "High-quality wireless headphones with noise cancellation.",
    availability: true,
    rentalPrice: 15,
    rentalDurationOptions: [1, 3, 6],
    material: "Plastic",
    weight: 0.3,
    stockQuantity: 20,
    location: "Warehouse G",
    ratings: {
      averageRating: 4.8,
      numberOfRatings: 230,
    },
  },
  {
    ItemId: 16,
    name: "Gaming Mouse",
    category: "Electronics",
    image: "https://example.com/images/gaming-mouse.jpg",
    newPrice: 50,
    oldPrice: 70,
    color: "Red",
    description: "A high-precision gaming mouse for enhanced gameplay.",
    availability: true,
    rentalPrice: 8,
    rentalDurationOptions: [1, 3, 6],
    material: "Plastic",
    weight: 0.2,
    stockQuantity: 35,
    location: "Warehouse H",
    ratings: {
      averageRating: 4.6,
      numberOfRatings: 180,
    },
  },
  {
    ItemId: 17,
    name: "Table Lamp",
    category: "Decor",
    image: "https://example.com/images/table-lamp.jpg",
    newPrice: 45,
    oldPrice: 60,
    color: "Yellow",
    description: "A stylish table lamp to brighten up your workspace.",
    availability: true,
    rentalPrice: 5,
    rentalDurationOptions: [1, 2, 4],
    material: "Metal",
    weight: 2.5,
    stockQuantity: 28,
    location: "Warehouse I",
    ratings: {
      averageRating: 4.2,
      numberOfRatings: 75,
    },
  },
  {
    ItemId: 18,
    name: "Digital Alarm Clock",
    category: "Electronics",
    image: "https://example.com/images/digital-alarm-clock.jpg",
    newPrice: 25,
    oldPrice: 30,
    color: "Black",
    description: "A compact digital alarm clock with multiple features.",
    availability: true,
    rentalPrice: 3,
    rentalDurationOptions: [1, 2, 3],
    material: "Plastic",
    weight: 0.4,
    stockQuantity: 45,
    location: "Warehouse J",
    ratings: {
      averageRating: 4.3,
      numberOfRatings: 110,
    },
  },
  {
    ItemId: 19,
    name: "Sports Water Bottle",
    category: "Accessories",
    image: "https://example.com/images/sports-water-bottle.jpg",
    newPrice: 20,
    oldPrice: 25,
    color: "Blue",
    description: "A leak-proof sports water bottle with a convenient flip lid.",
    availability: true,
    rentalPrice: 2,
    rentalDurationOptions: [1, 2, 3],
    material: "Plastic",
    weight: 0.6,
    stockQuantity: 60,
    location: "Warehouse K",
    ratings: {
      averageRating: 4.5,
      numberOfRatings: 90,
    },
  },
  {
    ItemId: 20,
    name: "Ceramic Vase",
    category: "Decor",
    image: "https://example.com/images/ceramic-vase.jpg",
    newPrice: 55,
    oldPrice: 70,
    color: "White",
    description: "An elegant ceramic vase perfect for floral arrangements.",
    availability: true,
    rentalPrice: 6,
    rentalDurationOptions: [2, 4, 6],
    material: "Ceramic",
    weight: 1.8,
    stockQuantity: 22,
    location: "Warehouse L",
    ratings: {
      averageRating: 4.4,
      numberOfRatings: 65,
    },
  },
];
